### ISSUE TITLE
Products with variations create an error

### ISSUE THREAD

**Issue by stuffo** [dchun/WooCommerce-RFQ#2]
When a product has variations you can't RFQ it as you get a error message that options need to be supplied.

**Comment by dchun** [comment]
Can you provide an example along with a screenshot of the variation options set for the product in the backend?

**Comment by stuffo** [comment]
Sure. In my case it never works with options, you can just create random ones. The error I get is  "Please choose product options" when trying to RFQ.  

![variables-1](https://cloud.githubusercontent.com/assets/5367857/21272622/b3d82ef8-c3c8-11e6-8a9c-88cecdace01c.png)

![variables-2](https://cloud.githubusercontent.com/assets/5367857/21272635/c366cd66-c3c8-11e6-9923-9c20d08f3aee.png)

**Comment by dchun** [comment]
You might want to make sure that the product is purchasable with your options first. Then turn into an inquirable product. WC is finicky with options settings for variable products and doesn't display an add to cart button (which the plugin depends on) unless they are just right.

Check out this example of options on a variable product that works properly: https://demo.boopis.com/wp_mprfq/?product=ship-your-idea-2&added-to-quote=40

**Comment by stuffo** [comment]
When I put in a price it works fine. I choose a variation and I can add it to the cart. See here:

![variables-3](https://cloud.githubusercontent.com/assets/5367857/21273477/77763096-c3cc-11e6-8f96-7a66f1edbf6b.png)

Your example on your site works fine... the only difference I see is that I only have one variation field and you have two. Could this be an issue?
