### ISSUE TITLE
Allow mixing of RFQ and Buyable variations

### ISSUE THREAD

**Issue by stuffo** [dchun/WooCommerce-RFQ#3]
Currently a product and its variations can only be either RFQable or Buyable. You can't mix based on variations.

In my case I sell Software with variations of "30-day Test-Version" and "Full Version". The 30-day version is buyable, but the Full-Version needs to be RFQed.

**Comment by dchun** [comment]
You're welcome to make a pull request to add the feature you are looking for. Until then, I am closing this issue.
